-- Sélectionnez tous les champs de `categ` ordonnés par `name` ascendant
-- Séléctionnez `idcateg` et `name` de `categ` quand `idcateg` vaut 4
-- Séléctionnez `idcateg` et `name` de `categ` quand `idcateg` se trouve entre 2 et 4
-- Séléctionnez `idcateg` et `name` de `categ` quand `idcateg` se trouve est 1, 3 ou 5 ordonné par `name` descendant